[build]
  command = "gunicorn -b 0.0.0.0:8080 wsgi:app"
	publish = "projects/notes-online"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/edit/*"
  to = "/edit.html"
  status = 200