[build]
  command = "pip install -r requirements.txt && python main.py"
  publish = "projects/notes-online"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/edit/*"
  to = "/edit.html"
  status = 200
