[build]
  command = "python -m http.server"
  publish = "projects/notes-online"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/edit/*"
  to = "/edit.html"
  status = 200
